# Generated by Django 2.0.5 on 2019-05-21 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('period', models.IntegerField(blank=True, choices=[(1, 'Monthly'), (2, 'Quarterly'), (3, 'Half Year'), (4, 'Yearly')], default=1, help_text='1->Monthly, 2->Quarterly, 3->Half Year, 4->Yearly', null=True)),
                ('features', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
    ]
